version: '3.8'

services:
  app:
    image: patientor-frontend-dev
    container_name: patientor-frontend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 5173:5173
    environment:
      - VITE_API_BASE_URL=http://localhost:3001/api
